export const wishlistActionTypes = {
  ADD_ITEM_To_WISHLIST: "ADD_ITEM_To_WISHLIST",
  TOGGLE_WISHLIST_DROPDOWN: "TOGGLE_WISHLIST_DROPDOWN",
  MOVE_ITEM_WISHLIST_TO_CART: "MOVE_ITEM_WISHLIST_TO_CART",
  REMOVE_ITEM_FROM_WISHLIST: "REMOVE_ITEM_FROM_WISHLIST",
  MOVE_ITEM_CART_TO_WISHLIST: "MOVE_ITEM_CART_TO_WISHLIST",
};
